### ISSUE TITLE
feature enable between 2 dates

### ISSUE THREAD

**Issue by lobor** [WitoDelnat/keat#5]
Hi, great lib.
I want for christmas show specific design. I can see halloween exemple in README with `{ OR: ["preview", "2022-11-08"] }` this work good.
I want disable this feature between 2 date, for exemple `{ OR: ["between", "2022-11-20", "2022-12-27"] }`
I think i can do this with audience without use user.

**Comment by WitoDelnat** [comment]
Hi Lobor!

I just saw your issue - thanks for considering Keat! I'll work on something this evening as this plugin is relatively easy to add.

For the API I'll follow [the ISO 8601 specification to describe time intervals](https://en.wikipedia.org/wiki/ISO_8601#:~:text=Start%20and%20end%2C%20such%20as%20%222007%2D03%2D01T13%3A00%3A00Z/2008%2D05%2D11T15%3A30%3A00Z%22).

**Comment by WitoDelnat** [comment]
Hi again Lobor,

I've just released a v1.0.0-rc.5 which contains a `timeInterval` plugin.

Example usage:

```
import { keatReact, timeInterval } from "keat";

export const { useKeat } = keatReact({
  features: { demo: "2022-11-15T21:05/2022-11-15T21:10" },
  plugins: [timeInterval()],
});
```

For your example it would simply become `"2022-11-20/2022-12-27"` as you can omit the hours and minutes.

Would you mind helping me out? I'm curious as to how you found this library. Just by Googling or in another way?

Please let me know if you have other issues.

**Comment by lobor** [comment]
ok great thanks, finaly i create custom plugin for this
```typescript
const { useKeat: useFeature, FeatureBoundary: Feature } = keatReact({
  features: {
    cgpChargePlan: false,
    isChristmas: "christmasMonth",
  } as const,
  plugins: [
    {
      onEval: ({ rules }, { setResult }) => {
        rules.forEach((r: any) => {
          if (r === "christmasMonth") {
            setResult(getMonth(Date.now()) === 11);
          }
        });
      },
    },
  ],
});
```
your solution is great but needed change year for next christmas, i need check automaticaly

I found your repo in reddit, it seems to me
the feature tag is important workflow when back and front not ready in same time.

sorry for my english, i am a bad english speaker

**Comment by WitoDelnat** [comment]
That's really awesome! Great that you managed to solve it with a custom plugin. That was always the intention of Keat. 

No worry about your English - I understand everything clearly. I'll close the issue for now, but should you ever need more help then just give me a shout!

**Comment by lobor** [comment]
i think it's important to add documentation how create plugin and explain the mechanism, may add example with different workflow.
Christmas date can be an example, or use keat like state role management (like use role or rights)

**Comment by WitoDelnat** [comment]
Thank you for the feedback. I agree that plugins need better docs. I hope to have some time during the Christmas period as I also have a minor rework in mind to plugins to make it easier as there are some edge cases introduced by multi-variates.
